/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.eryzaa;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2~PC27
 */
public class prelimexam extends javax.swing.JFrame {

    /**
     * Creates new form prelimexam
     */
    public prelimexam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtp1 = new javax.swing.JTextField();
        txtp2 = new javax.swing.JTextField();
        txth1 = new javax.swing.JTextField();
        txth2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txts1 = new javax.swing.JTextField();
        txts2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("p1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setText("p2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(txtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, -1));
        getContentPane().add(txtp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, -1));

        txth1.setText("5");
        getContentPane().add(txth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        txth2.setText("5");
        txth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txth2ActionPerformed(evt);
            }
        });
        getContentPane().add(txth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel3.setText("HB");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel4.setText("HB");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        txts1.setText("0");
        getContentPane().add(txts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        txts2.setText("0");
        txts2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txts2ActionPerformed(evt);
            }
        });
        getContentPane().add(txts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel5.setText("Score");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel6.setText("Score");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txts2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txts2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txts2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           System.out.println( "Rock- [1]");
           System.out.println( "Paper- [2]");
           System.out.println( "Scisscors- [3]");
       int h1 = Integer.parseInt(txth1.getText());  
       int h2 = Integer.parseInt(txth2.getText());
       int score1=  Integer.parseInt(txts1.getText());
       int score2 =  Integer.parseInt(txts2.getText());
        int player1 = Integer.parseInt(txtp1.getText());
        int player2 = Integer.parseInt(txtp2.getText());
        txtp1.setText("");
        txtp2.setText("");
       
        
        if (player1 == player2) 
        {
             JOptionPane.showMessageDialog(null, "Draw", "Rock, Paper, and Scisscors",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else if (player1 == 1 && player2== 2  || player1 == 2 && player2 == 3 || player1 == 3 && player2 ==1)
        {
        
           JOptionPane.showMessageDialog(null, "Player 2 Wins", "Rock, Paper, and Scisscors",JOptionPane.INFORMATION_MESSAGE);
           int hb  = h2 - 1 ;
           int s1 = score1 +1;
           txth2.setText(""+hb);
           txts2.setText(""+s1);
           
        }
        
         else if (player1 == 1 && player2== 3  || player1 == 2 && player2 == 1 || player1 == 3 && player2 ==2) 
         { 
           
           JOptionPane.showMessageDialog(null, "Player 1 Wins", "Rock, Paper, and Scisscors",JOptionPane.INFORMATION_MESSAGE);
         int hb  = h1 - 1 ;
           int s2 = score1 +1;
           txth1.setText(""+hb);
           txts1.setText(""+s2);
         }
        
         else
         {
             JOptionPane.showMessageDialog(null, "Incorrect Output", "Rock, Paper, and Scisscors",JOptionPane.INFORMATION_MESSAGE);  
         }
          if (h1==0)
          {
            JOptionPane.showMessageDialog(null, "Player 1 Wins", "Game over",JOptionPane.INFORMATION_MESSAGE);  
            int hb = 5;
          }
             if (h2==0)
          {
            JOptionPane.showMessageDialog(null, "Player2 Wins", "Game over",JOptionPane.INFORMATION_MESSAGE);  
            int hb = 5;
          }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txth2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txth2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txth2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prelimexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prelimexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prelimexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prelimexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prelimexam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txth1;
    private javax.swing.JTextField txth2;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtp2;
    private javax.swing.JTextField txts1;
    private javax.swing.JTextField txts2;
    // End of variables declaration//GEN-END:variables
}
